default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # password: <%= ENV['HOTEL-API_PSQL_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: hotel-api_development
  # password: <%= ENV['HOTEL-API_PSQL_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: hotel-api_test
#  password: <%= ENV['HOTEL-API_PSQL_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: hotel-api_production
  username: hotel-api
  password: <%= ENV['HOTEL-API_DATABASE_PASSWORD'] %>
